### ISSUE TITLE
Flag for special exit code when changes are applied

### ISSUE THREAD

**Issue by jlaffaye** [dsully/macos-defaults#4]
I would like to know when the apply command is actually making changes.
To do that, we could return a special exit code when at least one change has been made.
This behaviour should be probably opt-in with a command line flag.

My goal is to use the exit code with the [`changed_when` clause of ansible](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_error_handling.html#defining-changed)

**Comment by dsully** [comment]
Hi - thanks for request. I'll have to think about how to handle this properly.

**Comment by dsully** [comment]
Merged as fdd5255 - the `apply` subcommand now takes an `--exit-code` flag that defaults to `0`.
